### ISSUE TITLE
will it work for  multivariate  time series classification for example mixture of categorical and continues data? 

### ISSUE THREAD

**Issue by Sandy4321** [krzjoa/sciquence#1]
will it work for  multivariate  time series classification for example mixture of categorical and continues data? 
	for example at time t1 we have observation: red, 2.4 , 5, 12.456 and time t2: green, 3.5, 2, 45.78; time t3: black, 5.6, 7, 23.56; t4: red, 2.1, 5, 12.6 ?

**Comment by krzjoa** [comment]
Which method do you want to use?

**Comment by Sandy4321** [comment]
Classifiers: SAX-VSM classifier
And warping

**Comment by krzjoa** [comment]
Unfortunately, these methods are suitable for univariate time series only. 
In such a case, the thing you need is probably a Recurrent Neural Network 😎

**Comment by krzjoa** [comment]
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.715.4227&rep=rep1&type=pdf
Obviously, you can find references in sciquence docs :smirk:

**Comment by krzjoa** [comment]
I didn't know the first one, but if it comes to the second one, my implementation should work roughly the same :cowboy_hat_face:
